select * from globalsuperstore;
USE global_super_store;
SHOW TABLES;
SELECT `ORDER ID`,REGION
FROM GLOBALSUPERSTORE
WHERE REGION = 'WEST';

SELECT 'ORDER ID',CATEGORY
FROM globalsuperstore
WHERE CATEGORY = 'FURNITURE';

SELECT `ORDER ID`,SALES
FROM globalsuperstore
WHERE SALES >500;

select 'ORDER ID',CITY
FROM globalsuperstore
WHERE CITY = 'NEW YORK CITY';

-- CONDITIONAL FILTERING
SELECT 'ORDER ID',PROFIT
FROM globalsuperstore
WHERE Profit <0;

SELECT 'ORDER ID',DISCOUNT
FROM globalsuperstore
WHERE DISCOUNT >0.2;

SELECT 'ORDER ID',QUANTITY 
FROM globalsuperstore
WHERE QUANTITY BETWEEN 3 AND 7;

SELECT 'ORDER ID',SHIPPING
FROM globalsuperstore
WHERE SHIPPING = 'SECOND CLASS';

SELECT 'ORDER ID',STATE
FROM globalsuperstore
WHERE STATE IN ('CALIFORNIA','TEXAS');

-- ADVANCED WHERE
SELECT 'ORDER ID',CATEGORY,SALES
FROM globalsuperstore
WHERE CATEGORY = 'TECHNOLOGY' AND SALES >1000;

SELECT 'ORDER ID',REGION,PROFIT
FROM globalsuperstore
WHERE REGION = 'EAST' OR PROFIT <0;

SELECT 'ORDER ID',CUSTOMER_NAME
FROM globalsuperstore
WHERE CUSTOMER_NAME LIKE 'A%';

SELECT 'ORDER ID',PRODUCT_NAME
FROM globalsuperstore
WHERE PRODUCT_NAME LIKE '%CHAIR%'; 

SELECT 'ORDER ID',POSTAL_CODE
FROM globalsuperstore
WHERE POSTAL_CODE IS NULL;

-- GROUPED BY ( AGGREGATE)
SELECT sum(SALES) AS TOTAL_SALES
FROM globalsuperstore
GROUP BY REGION;

SELECT sum(PROFIT) AS TOTAL_PROFIT
FROM globalsuperstore
GROUP BY CATEGORY;

SELECT SUB_CATEGORY,  SUM(QUANTITY) AS TOTAL_QUANTITY
FROM globalsuperstore
GROUP BY SUB_CATEGORY;

SELECT Ship_Mode,count(*) AS ORDER_COUNT
FROM globalsuperstore
GROUP BY Ship_Mode;

SELECT CUSTOMER_NAME, AVG(Sales) AS Avg_Sales
from globalsuperstore
group by Customer_Name;

-- INTERMEDIATE GROUP BY
SELECT Region,Category,SUM(Sales) AS Total_Sales,SUM(Profit) AS Total_Profit
FROM globalsuperstore
GROUP BY Region, Category;

SELECT Region, COUNT(DISTINCT Customer_Name) AS Customer_Count
from globalsuperstore
GROUP BY Region;

SELECT Segment, AVG(DISCOUNT) AS Avg_Discount
FROM globalsuperstore
GROUP BY Segment;

SELECT Sub_Category, MAX(Sales) AS Max_Sales
FROM globalsuperstore
GROUP BY Sub_Category;

SELECT Category, MIN(Profit) AS Min_Profit
FROM globalsuperstore
GROUP BY Category;

-- section 3 order by
SELECT SALES
 FROM globalsuperstore
 ORDER BY Sales ASC;
 
SELECT PROFIT
 FROM globalsuperstore
 ORDER BY Profit DESC;
 
SELECT ORDER_DATE
 FROM globalsuperstore
 ORDER BY Order_Date DESC;
 
SELECT CUSTOMER_NAME
 FROM globalsuperstore
 ORDER BY Customer_Name ASC;
 
SELECT CATEGORY
 FROM globalsuperstore
 ORDER BY Category ASC;

-- MULTIPLE COLUMN SORTING
SELECT REGION
FROM globalsuperstore
ORDER BY Region ASC, Sales DESC;

SELECT STATE,CITY
FROM globalsuperstore
ORDER BY State ASC, City ASC;

SELECT SHIP_MODE,ORDER_DATE
FROM globalsuperstore
ORDER BY Ship_Mode ASC, Order_Date ASC;

SELECT SEGMENT,SALES
FROM globalsuperstore
ORDER BY Segment DESC, Sales ASC;

SELECT CATEGORY,PROFIT
FROM globalsuperstore
ORDER BY Category ASC, Profit ASC;
-- 1
SELECT `CUSTOMER ID`,`ORDER ID`,SUM(SALES) AS TOTAL_SALES
FROM GLOBALSUPERSTORE
GROUP BY `CUSTOMER ID`,`ORDER ID`
HAVING TOTAL_SALES
ORDER BY TOTAL_SALES DESC LIMIT 5;
-- 2
SELECT `SUB-CATEGORY`,COUNT(QUANTITY) AS TOTAL_QUANTITY
FROM globalsuperstore
GROUP BY `SUB-CATEGORY`
HAVING TOTAL_QUANTITY>100
ORDER BY TOTAL_QUANTITY DESC LIMIT 5;
-- 3
SELECT REGION,AVG(SALES) AS AVG_SALES
FROM globalsuperstore
GROUP BY REGION
HAVING AVG_SALES>300
ORDER BY AVG(SALES) DESC;
-- 4
SELECT `CUSTOMER NAME`,SUM(PROFIT) AS TOTAL_PROFIT
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING TOTAL_PROFIT<0
ORDER BY TOTAL_PROFIT ASC;
-- 5
SELECT CATEGORY,SUM(SALES) AS TOTAL_SALES
FROM globalsuperstore
GROUP BY CATEGORY
HAVING TOTAL_SALES>5000
ORDER BY TOTAL_SALES DESC LIMIT 3;
-- 6
SELECT `SUB-CATEGORY`,SUM(PROFIT) AS TOTAL_PROFIT
FROM globalsuperstore
GROUP BY `SUB-CATEGORY`
HAVING TOTAL_PROFIT>0
ORDER BY TOTAL_PROFIT ASC;
-- 7
SELECT `CUSTOMER NAME`,AVG(DISCOUNT) AS AVG_DISCOUNT
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING AVG_DISCOUNT>0.2;
-- 8
SELECT REGION,COUNT(QUANTITY) AS TOTAL_QUANTITY
FROM globalsuperstore
GROUP BY REGION
HAVING TOTAL_QUANTITY>200
ORDER BY TOTAL_QUANTITY DESC;
-- 9
SELECT `CUSTOMER NAME`,SUM(SALES) AS TOTAL_SALES
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING TOTAL_SALES>3000
ORDER BY TOTAL_SALES DESC LIMIT 5;
-- 10
SELECT `SUB-CATEGORY`,MAX(DISCOUNT) AS MAX_DISCOUNT
FROM globalsuperstore
GROUP BY `SUB-CATEGORY`
HAVING MAX_DISCOUNT>0.5;
-- 11
SELECT `CUSTOMER NAME`,COUNT(`ORDER ID`) AS ORDERS
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING ORDERS>3
ORDER BY `CUSTOMER NAME` ASC;
-- 12
SELECT CATEGORY,COUNT(QUANTITY) AS TOTAL_QUANTITY
FROM globalsuperstore
GROUP BY CATEGORY
HAVING TOTAL_QUANTITY>150
ORDER BY TOTAL_QUANTITY LIMIT 2;
-- 13
SELECT REGION,SUM(PROFIT) AS TOTAL_PROFIT
FROM globalsuperstore
GROUP BY REGION
HAVING TOTAL_PROFIT<1000
ORDER BY TOTAL_PROFIT;
-- 14
SELECT `CUSTOMER NAME`,SUM(SALES) AS TOTAL_SALES
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING TOTAL_SALES>2000
ORDER BY TOTAL_SALES;

-- 15
SELECT `SUB-CATEGORY`,AVG(QUANTITY) AS AVG_QUANTITY
FROM globalsuperstore
GROUP BY `SUB-CATEGORY`
HAVING AVG_QUANTITY>3
ORDER BY AVG_QUANTITY;
-- 16
SELECT `CUSTOMER NAME`,SUM(PROFIT) AS TOTAL_PROFIT
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING TOTAL_PROFIT>1000
ORDER BY TOTAL_PROFIT DESC LIMIT 4;
-- 17
SELECT REGION,MAX(SALES) AS MAX_SALES
FROM globalsuperstore
GROUP BY REGION
HAVING MAX_SALES>2000;
-- 18
SELECT `SUB-CATEGORY`,AVG(PROFIT) AS AVG_PROFIT
FROM globalsuperstore
GROUP BY `SUB-CATEGORY`
HAVING AVG_PROFIT<50
ORDER BY AVG_PROFIT ASC;
-- 19
SELECT REGION,SUM(SALES) AS TOTAL_SALES
FROM globalsuperstore
GROUP BY REGION
HAVING TOTAL_SALES>10000
ORDER BY TOTAL_SALES DESC LIMIT 3;
-- 20
SELECT `CUSTOMER NAME`,MIN(PROFIT) AS MIN_PROFIT
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING MIN_PROFIT<0;
-- 21
SELECT CATEGORY,AVG(DISCOUNT) AS AVG_DISCOUNT
FROM globalsuperstore
GROUP BY CATEGORY
HAVING AVG_DISCOUNT>0.25
ORDER BY AVG_DISCOUNT DESC;
-- 22
SELECT `SUB-CATEGORY`,SUM(PROFIT) AS TOTAL_PROFIT
FROM globalsuperstore
GROUP BY `SUB-CATEGORY`
HAVING TOTAL_PROFIT>500
ORDER BY TOTAL_PROFIT DESC LIMIT 5;
-- 23
SELECT `CUSTOMER NAME`,COUNT(QUANTITY) AS TOTAL_QUANTITY
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING TOTAL_QUANTITY>50
ORDER BY TOTAL_QUANTITY;
-- 24
SELECT REGION,MIN(DISCOUNT) AS MIN_DISCOUNT
FROM globalsuperstore
GROUP BY REGION
HAVING MIN_DISCOUNT;
-- 25
SELECT `CUSTOMER NAME`,COUNT(QUANTITY) AS TOTAL_QUANTITY
FROM globalsuperstore
GROUP BY `CUSTOMER NAME`
HAVING TOTAL_QUANTITY>30
ORDER BY TOTAL_QUANTITY DESC LIMIT 3;










































	
